# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS DELTA_TRAINING.EMPL_PT_36HR_FLAG(WEEK_DT TIMESTAMP,
# MAGIC EMPLOYEE_ID INT,
# MAGIC LOCATION_ID INT,
# MAGIC EMPL_13WK_AVG_HRS_WORKED INT,
# MAGIC FLAG INT,
# MAGIC LOAD_TSTMP TIMESTAMP) USING DELTA;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS DELTA_TRAINING.EMPL_36HR_FLAG(WEEK_DT TIMESTAMP,
# MAGIC EMPLOYEE_ID INT,
# MAGIC LOCATION_ID INT,
# MAGIC EMPL_13WK_AVG_HRS_WORKED INT,
# MAGIC FLAG INT,
# MAGIC LOAD_TSTMP TIMESTAMP) USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from DELTA_TRAINING.EMPL_PT_36HR_FLAG;

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from DELTA_TRAINING.EMPL_36HR_FLAG;

# COMMAND ----------


