# Databricks notebook source
# COMMAND ----------

CREATE DATABASE IF NOT EXISTS DELTA_TRAINING;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.SLSCMP_STORE(LOCATION_ID INT,
LOCATION_TYPE_ID INT,
FIRST_SALE_DT TIMESTAMP,
FIRST_MEASURED_SALE_DT TIMESTAMP,
LAST_SALE_DT TIMESTAMP,
SALES_CURR_FLAG INT,
COMP_EFF_DT TIMESTAMP,
COMP_END_DT TIMESTAMP,
COMP_CURR_FLAG INT,
LOAD_DT TIMESTAMP) USING DELTA;