# Databricks notebook source
# MAGIC %run "./udf_informatica"

# COMMAND ----------


from pyspark.sql.types import *

spark.sql("use DELTA_TRAINING")
spark.sql("set spark.sql.legacy.timeParserPolicy = LEGACY")


# COMMAND ----------
# DBTITLE 1, SLSCMP_STORE_0


df_0=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        LOCATION_TYPE_ID AS LOCATION_TYPE_ID,
        FIRST_SALE_DT AS FIRST_SALE_DT,
        FIRST_MEASURED_SALE_DT AS FIRST_MEASURED_SALE_DT,
        LAST_SALE_DT AS LAST_SALE_DT,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        COMP_EFF_DT AS COMP_EFF_DT,
        COMP_END_DT AS COMP_END_DT,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        LOAD_DT AS LOAD_DT,
        monotonically_increasing_id() AS Monotonically_Increasing_Id 
    FROM
        SLSCMP_STORE""")

df_0.createOrReplaceTempView("SLSCMP_STORE_0")

# COMMAND ----------
# DBTITLE 1, ASQ_SITE_PROFILE_RPT_1


df_1=spark.sql("""
    SELECT
        LOCATION_ID AS LOCATION_ID,
        FIRST_SALE_DT AS FIRST_SALE_DT,
        FIRST_MEASURED_SALE_DT AS FIRST_MEASURED_SALE_DT,
        LAST_SALE_DT AS LAST_SALE_DT,
        SALES_CURR_FLAG AS SALES_CURR_FLAG,
        COMP_EFF_DT AS COMP_EFF_DT,
        COMP_END_DT AS COMP_END_DT,
        COMP_CURR_FLAG AS COMP_CURR_FLAG,
        Monotonically_Increasing_Id AS Monotonically_Increasing_Id 
    FROM
        SLSCMP_STORE_0""")

df_1.createOrReplaceTempView("ASQ_SITE_PROFILE_RPT_1")

# COMMAND ----------
# DBTITLE 1, SITE_PROFILE_RPT


spark.sql("""INSERT INTO SITE_PROFILE_RPT SELECT LOCATION_ID AS LOCATION_ID,
null AS LOCATION_TYPE_ID,
null AS LOCATION_TYPE_DESC,
null AS STORE_NBR,
null AS STORE_NAME,
null AS STORE_TYPE_ID,
null AS STORE_TYPE_DESC,
null AS PARENT_LOCATION_ID,
null AS LOCATION_NBR,
null AS COMPANY_ID,
null AS COMPANY_DESC,
null AS SUPER_REGION_ID,
null AS SUPER_REGION_DESC,
null AS REGION_ID,
null AS REGION_DESC,
null AS DISTRICT_ID,
null AS DISTRICT_DESC,
null AS SITE_ADDRESS,
null AS SITE_CITY,
null AS SITE_COUNTY,
null AS STATE_CD,
null AS STATE_NAME,
null AS POSTAL_CD,
null AS COUNTRY_CD,
null AS COUNTRY_NAME,
null AS GEO_LATITUDE_NBR,
null AS GEO_LONGITUDE_NBR,
null AS PETSMART_DMA_CD,
null AS PETSMART_DMA_DESC,
null AS SITE_MAIN_TELE_NO,
null AS SITE_GROOM_TELE_NO,
null AS SITE_FAX_NO,
null AS SITE_EMAIL_ADDRESS,
null AS STORE_OPEN_CLOSE_FLAG,
null AS SFT_OPEN_DT,
null AS OPEN_DT,
null AS GR_OPEN_DT,
null AS CLOSE_DT,
null AS SITE_SALES_FLAG,
SALES_CURR_FLAG AS SALES_CURR_FLAG,
null AS SITE_OPEN_YRS_AMT,
FIRST_SALE_DT AS FIRST_SALE_DT,
FIRST_MEASURED_SALE_DT AS FIRST_MEASURED_SALE_DT,
LAST_SALE_DT AS LAST_SALE_DT,
COMP_CURR_FLAG AS COMP_CURR_FLAG,
COMP_EFF_DT AS COMP_EFF_DT,
COMP_END_DT AS COMP_END_DT,
null AS TP_LOC_FLAG,
null AS TP_ACTIVE_CNT,
null AS TP_START_DT,
null AS HOTEL_FLAG,
null AS HOTEL_OPEN_DT,
null AS DAYCAMP_FLAG,
null AS VET_FLAG,
null AS TIME_ZONE_ID,
null AS TIME_ZONE,
null AS SQ_FEET_RETAIL,
null AS SQ_FEET_TOTAL,
null AS TRADE_AREA,
null AS DELV_SERVICE_CLASS_ID,
null AS PICK_SERVICE_CLASS_ID,
null AS REPL_DC_NBR,
null AS REPL_FISH_DC_NBR,
null AS REPL_FWD_DC_NBR,
null AS PROMO_LABEL_CD,
null AS PRICE_ZONE_ID,
null AS PRICE_ZONE_DESC,
null AS PRICE_AD_ZONE_ID,
null AS PRICE_AD_ZONE_DESC,
null AS EQUINE_MERCH_ID,
null AS EQUINE_MERCH_DESC,
null AS EQUINE_SITE_ID,
null AS EQUINE_SITE_DESC,
null AS EQUINE_SITE_OPEN_DT,
null AS LOYALTY_PGM_TYPE_ID,
null AS LOYALTY_PGM_TYPE_DESC,
null AS LOYALTY_PGM_STATUS_ID,
null AS LOYALTY_PGM_STATUS_DESC,
null AS LOYALTY_PGM_START_DT,
null AS LOYALTY_PGM_CHANGE_DT,
null AS BP_COMPANY_NBR,
null AS BP_GL_ACCT,
null AS SITE_LOGIN_ID,
null AS SITE_MANAGER_ID,
null AS SITE_MANAGER_NAME,
null AS MGR_ID,
null AS MGR_DESC,
null AS DVL_ID,
null AS DVL_DESC,
null AS PURCH_GROUP_ID,
null AS PURCH_GROUP_NAME,
null AS TOTAL_SALES_RANKING_CD,
null AS MERCH_SALES_RANKING_CD,
null AS SERVICES_SALES_RANKING_CD,
null AS SALON_SALES_RANKING_CD,
null AS TRAINING_SALES_RANKING_CD,
null AS HOTEL_DDC_SALES_RANKING_CD,
null AS CONSUMABLES_SALES_RANKING_CD,
null AS HARDGOODS_SALES_RANKING_CD,
null AS SPECIALTY_SALES_RANKING_CD,
null AS DIST_MGR_NAME,
null AS DM_EMAIL_ADDRESS,
null AS DC_AREA_DIRECTOR_NAME,
null AS DC_AREA_DIRECTOR_EMAIL,
null AS DIST_SVC_MGR_NAME,
null AS DSM_EMAIL_ADDRESS,
null AS REGION_VP_NAME,
null AS RVP_EMAIL_ADDRESS,
null AS REGION_TRAINER_NAME,
null AS ASSET_PROTECT_NAME,
null AS ASSET_PROTECT_EMAIL,
null AS LP_SAFETY_DIRECTOR_NAME,
null AS LP_SAFETY_DIRECTOR_EMAIL,
null AS SR_LP_SAFETY_MGR_NAME,
null AS SR_LP_SAFETY_MGR_EMAIL,
null AS REGIONAL_LP_SAFETY_MGR_NAME,
null AS REGIONAL_LP_SAFETY_MGR_EMAIL,
null AS RETAIL_MANAGER_SAFETY_NAME,
null AS RETAIL_MANAGER_SAFETY_EMAIL,
null AS DC_GENERAL_MANAGER_NAME,
null AS DC_GENERAL_MANAGER_EMAIL,
null AS ASST_DC_GENERAL_MANAGER_NAME1,
null AS ASST_DC_GENERAL_MANAGER_EMAIL1,
null AS ASST_DC_GENERAL_MANAGER_NAME2,
null AS ASST_DC_GENERAL_MANAGER_EMAIL2,
null AS HR_MANAGER_NAME,
null AS HR_MANAGER_EMAIL,
null AS HR_SUPERVISOR_NAME1,
null AS HR_SUPERVISOR_EMAIL1,
null AS HR_SUPERVISOR_NAME2,
null AS HR_SUPERVISOR_EMAIL2,
null AS LEARN_SOLUTION_MGR_NAME,
null AS LEARN_SOLUTION_MGR_EMAIL,
null AS ADD_DT,
null AS DELETE_DT,
null AS UPDATE_DT,
null AS LOAD_DT FROM ASQ_SITE_PROFILE_RPT_1""")